database:
  url:
    host: localhost
    port: 5432
    db: project
    schema: digital_library
  credentials:
    username: lazarev
    password: 1234

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
    default-schema: ${database.url.schema}
    enabled: true
    parameters:
      schema: ${database.url.schema}
  datasource:
    url: jdbc:postgresql://${database.url.host}:${database.url.port}/${database.url.db}?currentSchema=${database.url.schema}
    username: ${database.credentials.username}
    password: ${database.credentials.password}
    driverClassName: org.postgresql.Driver

aws:
  bucket-name: digital-library
  access-key-id: accessKey1
  secret-access-key: verySecretKey1
  service-endpoint-url: http://0.0.0.0:8000/
  service-region: us-west-2